In [3]:
import numpy as np
import pandas as pd

# numpy

In [19]:
np.random.randn(5)

array([ 0.25279453,  0.52873645, -0.19206556,  0.37710147,  0.85172484])

In [20]:
np.random.rand(5)

array([ 0.38215362,  0.94703115,  0.20458847,  0.12965262,  0.96428674])

创建未初始化的array，更快捷和低代价(malloc vs. cmalloc)?

In [21]:
np.empty((3,2))

array([[  4.24399158e-314,   8.48798317e-314],
       [  4.24399158e-314,   8.48798317e-314],
       [  4.24399158e-314,   8.48798317e-314]])

In [22]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [23]:
np.tile(np.array([[1,2],[3,4]]),4)

array([[1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4]])

In [24]:
np.tile(np.array([[1,2],[3,4]]),(3,5))

array([[1, 2, 1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4, 3, 4]])

In [25]:
sar=np.array(['Goodbye','Welcome','Tata','Goodnight'])
sar.dtype

dtype('<U9')

In [26]:
ran = np.random.rand(5)

In [27]:
ran3 = ran[0], ran[2], ran[4]

In [28]:
type(ran3)

tuple

In [29]:
r_a = np.arange(5)[::-1]
r_a

array([4, 3, 2, 1, 0])

In [30]:
r_a[[2,4,1,0]]

array([2, 0, 3, 4])

In [35]:
ar = np.arange(8);ar

array([0, 1, 2, 3, 4, 5, 6, 7])

In [36]:
arc = ar.copy()
arc[:]=0
print(ar)
print(arc)

[0 1 2 3 4 5 6 7]
[0 0 0 0 0 0 0 0]


In [37]:
ar = range(1000)
%timeit [ar[i]**3 for i in ar]

439 µs ± 24.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [38]:
ar = np.arange(10000)
%timeit ar**3

17.1 µs ± 56.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [39]:
l1 = np.array([True,False,True,False])
l2 = np.array([False,False,True, False])
np.logical_and(l1,l2)

array([False, False,  True, False], dtype=bool)

In [41]:
rgb = np.arange(30).reshape(2,3,5)

In [42]:
rgb

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [43]:
rgb = rgb.transpose(0,2,1)

In [44]:
rgb

array([[[ 0,  5, 10],
        [ 1,  6, 11],
        [ 2,  7, 12],
        [ 3,  8, 13],
        [ 4,  9, 14]],

       [[15, 20, 25],
        [16, 21, 26],
        [17, 22, 27],
        [18, 23, 28],
        [19, 24, 29]]])

In [45]:
rgb.shape

(2, 5, 3)

In [46]:
rgb.flatten()

array([ 0,  5, 10,  1,  6, 11,  2,  7, 12,  3,  8, 13,  4,  9, 14, 15, 20,
       25, 16, 21, 26, 17, 22, 27, 18, 23, 28, 19, 24, 29])

In [48]:
rgb.sum(axis=0)

array([[15, 25, 35],
       [17, 27, 37],
       [19, 29, 39],
       [21, 31, 41],
       [23, 33, 43]])

In [49]:
rgb.mean(axis = 0)

array([[  7.5,  12.5,  17.5],
       [  8.5,  13.5,  18.5],
       [  9.5,  14.5,  19.5],
       [ 10.5,  15.5,  20.5],
       [ 11.5,  16.5,  21.5]])

In [3]:
ar = np.array([13,14,15])
ar.shape

(3,)

In [4]:
ar = ar[:, np.newaxis]

In [5]:
ar.shape

(3, 1)

In [6]:
ar.flatten()

array([13, 14, 15])

In [7]:
ar

array([[13],
       [14],
       [15]])

In [8]:
ar = ar.flatten()

In [9]:
ar

array([13, 14, 15])

<p>np.sort : out-of-place</p>
<p>np.array.sort : in-place</p>

In [12]:
ar = np.arange(4,10)
ar.argmin() # indices of minimum

0

# pandas

## pandas data structure
- Series
- DataFrame
- Panel

```python
import pandas as pd
ser = pd.Series(data, index=idx)
```

In [14]:
ser = pd.Series(np.random.rand(7))
ser

0    0.063999
1    0.290539
2    0.208743
3    0.394024
4    0.212165
5    0.903497
6    0.488540
dtype: float64

In [16]:
import calendar as cal
monthNames = [cal.month_name[i] for i in range(1,7)]
months = pd.Series(np.arange(1,7), index=monthNames)
months

January     1
February    2
March       3
April       4
May         5
June        6
dtype: int32

In [17]:
months.index

Index(['January', 'February', 'March', 'April', 'May', 'June'], dtype='object')

In [19]:
months._data

SingleBlockManager
Items: Index(['January', 'February', 'March', 'April', 'May', 'June'], dtype='object')
IntBlock: 6 dtype: int32

In [20]:
stockPrices = {'GOOG':1180.97,'FB':62.57,'TWTR': 64.50, 'AMZN':358.69,'AAPL':500.6}

In [21]:
stockPricesSeries = pd.Series(stockPrices, index=['GOOG','FB','TWTR','AMZN','AAPL'],name='stockPrices')

In [22]:
stockPricesSeries

GOOG    1180.97
FB        62.57
TWTR      64.50
AMZN     358.69
AAPL     500.60
Name: stockPrices, dtype: float64

In [23]:
stockSummaries={
'AMZN': pd.Series([346.15,0.59,459,0.52,589.8,158.88],
index=['Closing price','EPS',
'Shares Outstanding(M)',
'Beta', 'P/E','Market Cap(B)']),
'GOOG': pd.Series([1133.43,36.05,335.83,0.87,31.44,380.64],
index=['Closing price','EPS','Shares Outstanding(M)',
'Beta','P/E','Market Cap(B)']),
'FB': pd.Series([61.48,0.59,2450,104.93,150.92],
index=['Closing price','EPS','Shares Outstanding(M)',
'P/E', 'Market Cap(B)']),
'YHOO': pd.Series([34.90,1.27,1010,27.48,0.66,35.36],
index=['Closing price','EPS','Shares Outstanding(M)',
'P/E','Beta', 'Market Cap(B)']),
'TWTR':pd.Series([65.25,-0.3,555.2,36.23],
index=['Closing price','EPS','Shares Outstanding(M)',
'Market Cap(B)']),
'AAPL':pd.Series([501.53,40.32,892.45,12.44,447.59,0.84],
index=['Closing price','EPS','Shares Outstanding(M)','P/E',
'Market Cap(B)','Beta'])}

In [25]:
stockDF = pd.DataFrame(stockSummaries)
stockDF

AAPL    AMZN       FB     GOOG    TWTR     YHOO
Beta                     0.84    0.52      NaN     0.87     NaN     0.66
Closing price          501.53  346.15    61.48  1133.43   65.25    34.90
EPS                     40.32    0.59     0.59    36.05   -0.30     1.27
Market Cap(B)          447.59  158.88   150.92   380.64   36.23    35.36
P/E                     12.44  589.80   104.93    31.44     NaN    27.48
Shares Outstanding(M)  892.45  459.00  2450.00   335.83  555.20  1010.00

In [4]:
spot = {'a':{'A':1,'B':2},
       'b':{'A':3,'B':4}}
spotDF = pd.DataFrame.from_dict(spot)
spotDF

a  b
A  1  3
B  2  4

In [4]:
spotDF['b']

A    3
B    4
Name: b, dtype: int64

In [5]:
spotDF[['b','a']]

b  a
A  3  1
B  4  2

In [6]:
spotDF.get('c', 'N/A')

'N/A'

In [7]:
spotDF['a']['A']

1

In [8]:
spotDF.a

A    1
B    2
Name: a, dtype: int64

In [10]:
spotDF.a.A

1

In [6]:
NYC_SnowAvgsData={'Months' :
['January','February','March',
'April', 'November', 'December'],
'Avg SnowDays' : [4.0,2.7,1.7,0.2,0.2,2.3],
'Avg Precip. (cm)' : [17.8,22.4,9.1,1.5,0.8,12.2],
'Avg Low Temp. (F)' : [27,29,35,45,42,32] }

In [16]:
NYC_DF = pd.DataFrame(NYC_SnowAvgsData, index=NYC_SnowAvgsData['Months'],
                     columns=['Avg SnowDays','Avg Precip. (cm)','Avg Low Temp. (F)'])
NYC_DF

Avg SnowDays  Avg Precip. (cm)  Avg Low Temp. (F)
January            4.0              17.8                 27
February           2.7              22.4                 29
March              1.7               9.1                 35
April              0.2               1.5                 45
November           0.2               0.8                 42
December           2.3              12.2                 32

In [15]:
NYC_DF.loc[:,'Avg SnowDays']

January     4.0
February    2.7
March       1.7
April       0.2
November    0.2
December    2.3
Name: Avg SnowDays, dtype: float64

In [17]:
SpotCrudePrices_2013_dict = {'Dubai':[108.1,100.8,106.1,106.7],
                             'U.K. Brent':[112.9,103.0,110.1,109.4],
                             'West Texas Intermediate':[94.4,94.2,105.8,97.4]
                            }

In [20]:
SpotCrudePrices_2013 =pd.DataFrame(SpotCrudePrices_2013_dict,
                                  index=['2013-Q1','2013-Q2','2013-Q3','2013-Q4'],
                                  columns=['Dubai','U.K. Brent','West Texas Intermediate'])

In [21]:
SpotCrudePrices_2013

Dubai  U.K. Brent  West Texas Intermediate
2013-Q1  108.1       112.9                     94.4
2013-Q2  100.8       103.0                     94.2
2013-Q3  106.1       110.1                    105.8
2013-Q4  106.7       109.4                     97.4

In [22]:
SpotCrudePrices_2013.columns=['Dubai','U_K Brent','West_Texas_Intermediate']

In [24]:
SpotCrudePrices_2013

Dubai  U_K Brent  West_Texas_Intermediate
2013-Q1  108.1      112.9                     94.4
2013-Q2  100.8      103.0                     94.2
2013-Q3  106.1      110.1                    105.8
2013-Q4  106.7      109.4                     97.4

In [26]:
SpotCrudePrices_2013.loc[:,SpotCrudePrices_2013.loc['2013-Q1']>110][::-1]

U_K Brent
2013-Q4      109.4
2013-Q3      110.1
2013-Q2      103.0
2013-Q1      112.9